### ISSUE TITLE
Undefined local variable or method 'license_acceptance_id' error in 2.23.0

### ISSUE THREAD

**Issue by drewhammond** [someara/kitchen-dokken#383]
## :ghost: Brief Description

Test kitchen fails to converge with an error about `license_acceptance_id` in 2.23.0. It works correctly in 2.22.2 (from Cinc Workstation 26.0.1)

## Version

`kitchen-dokken` v2.23.0 (from Cinc Workstation 26.0.2)

```
➜  ~ cinc version
Cinc Workstation version: 26.0.2
Cinc Client version: 19.2.12
Cinc Auditor version: 7.0.107
Cinc CLI version: 6.1.30
Biome version: unknown
Test Kitchen version: 4.0.0
Cookstyle version: 8.6.10
```

## Environment

macOS 26.4.1 (25E253), arm64
Using Berks, but also seems to happen with Policyfiles

## Steps to Reproduce

1. Create boilerplate repo
2. Run `kitchen destroy/create/converge`
3. Get error

kitchen.yml
```yaml
---
driver:
  name: dokken
  chef_version: latest
  privileged: true
  cgroupns_host: true
  platform: linux/arm64
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: dokken
  product_name: cinc

transport:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: ubuntu-24.04
    driver:
      image: dokken/ubuntu-24.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN rm /etc/apt/apt.conf.d/docker-clean

suites:
  - name: default
    run_list:
      - recipe[test::default]
```

## Expected Result

Converge without errors

## Actual Result

```
-----> Starting Test Kitchen (v4.0.0)
-----> Converging <default-ubuntu-2404>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [undefined local variable or method 'license_acceptance_id' for an instance of Kitchen::Provisioner::Dokken] on default-ubuntu-2404
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

## :heavy_plus_sign: Additional context

This seems to be related to https://github.com/test-kitchen/kitchen-dokken/pull/381

**Comment by hanwen-cluster** [comment]
I am facing the same issue: https://github.com/aws/aws-parallelcluster-cookbook/actions/runs/24691058827/job/76994660253?pr=3168
